### Introduction to pandas!

What we will learn in this notebook:
- how to open and read in a csv spreadsheet
- how to look at the data we have
- how to select columns
- how to do some math with them

First we need to import pandas as a library. We import the library and then tell Python to refer to it as `pd`:

In [1]:
import pandas as pd

### Reading spreadsheets

This is how you read a spreadsheet and assign it to a variable:

In [2]:
census_data = pd.read_csv('../data/2016_census_data.csv')

### Looking at your data

To look at the data you just read into Python, you can just run a cell with the name of the variable:

In [3]:
census_data

,geoid,name,total_population,median_income,median_home_value,educational_attainment,white_alone,black_alone,native,asian,native_hawaiian_pacific_islander,some_other_race_alone,two_or_more,hispanic_or_latino
0,34003001000,"Census Tract 10, Bergen County, New Jersey",6767,151641.0,680000.0,3045.0,5667.0,75.0,0.0,759.0,0.0,0.0,132.0,134.0
1,34003002100,"Census Tract 21, Bergen County, New Jersey",1522,114545.0,2000001.0,836.0,788.0,141.0,0.0,444.0,0.0,0.0,27.0,122.0
2,34003002200,"Census Tract 22, Bergen County, New Jersey",5389,90647.0,453800.0,1791.0,3481.0,99.0,9.0,1247.0,0.0,36.0,19.0,504.0
3,34003002300,"Census Tract 23, Bergen County, New Jersey",5828,112031.0,610000.0,2363.0,3595.0,89.0,37.0,1627.0,0.0,0.0,32.0,448.0
4,34003003100,"Census Tract 31, Bergen County, New Jersey",4946,76906.0,301900.0,1588.0,1803.0,306.0,0.0,1435.0,0.0,13.0,24.0,1365.0
5,34003003200,"Census Tract 32, Bergen County, New Jersey",5044,69531.0,322400.0,1417.0,1342.0,186.0,19.0,1882.0,0.0,6.0,64.0,1564.0
6,34003003300,"Census Tract 33, Bergen County, New Jersey",6638,97957.0,328100.0,1737.0,2437.0,400.0,0.0,2131.0,0.0,0.0,148.0,1522.0
7,34003003401,"Census Tract 34.01, Bergen County, New Jersey",2958,122650.0,385200.0,941.0,1704.0,109.0,0.0,520.0,0.0,0.0,36.0,589.0
8,34003003402,"Census Tract 34.02, Bergen County, New Jersey",3827,105776.0,356100.0,1237.0,1937.0,260.0,0.0,733.0,0.0,4.0,122.0,771.0
9,34003003500,"Census Tract 35, Bergen County, New Jersey",4100,52382.0,340200.0,891.0,886.0,502.0,16.0,1160.0,0.0,0.0,59.0,1493.0
10,34003004001,"Census Tract 40.01, Bergen County, New Jersey",3372,76979.0,331300.0,537.0,1635.0,145.0,0.0,169.0,0.0,42.0,80.0,1301.0
11,34003004002,"Census Tract 40.02, Bergen County, New Jersey",4976,78306.0,299700.0,1228.0,1694.0,462.0,0.0,561.0,0.0,20.0,29.0,2210.0
12,34003005000,"Census Tract 50, Bergen County, New Jersey",6238,84268.0,386200.0,1725.0,4095.0,0.0,9.0,444.0,0.0,23.0,103.0,1564.0
13,34003006100,"Census Tract 61, Bergen County, New Jersey",7159,63071.0,416900.0,2215.0,4288.0,124.0,0.0,728.0,0.0,71.0,121.0,1827.0
14,34003006201,"Census Tract 62.01, Bergen County, New Jersey",4416,49883.0,429500.0,1288.0,2307.0,68.0,0.0,602.0,0.0,70.0,74.0,1295.0
15,34003006202,"Census Tract 62.02, Bergen County, New Jersey",5073,81273.0,405900.0,2501.0,2795.0,145.0,0.0,1398.0,14.0,15.0,106.0,600.0
16,34003006300,"Census Tract 63, Bergen County, New Jersey",8013,54788.0,412300.0,2105.0,3108.0,297.0,0.0,589.0,0.0,21.0,320.0,3678.0
17,34003007001,"Census Tract 70.01, Bergen County, New Jersey",3899,100250.0,514100.0,1560.0,2146.0,28.0,8.0,1355.0,0.0,0.0,0.0,362.0
18,34003007002,"Census Tract 70.02, Bergen County, New Jersey",4751,143780.0,745300.0,1979.0,2482.0,86.0,0.0,2068.0,0.0,16.0,27.0,72.0
19,34003008000,"Census Tract 80, Bergen County, New Jersey",8745,117164.0,540700.0,3686.0,5641.0,64.0,14.0,2150.0,0.0,0.0,105.0,785.0
20,34003009100,"Census Tract 91, Bergen County, New Jersey",5007,150139.0,652800.0,2083.0,2961.0,11.0,0.0,1476.0,0.0,0.0,37.0,522.0
21,34003009200,"Census Tract 92, Bergen County, New Jersey",3446,168371.0,644700.0,1609.0,2728.0,36.0,6.0,547.0,0.0,0.0,59.0,76.0
22,34003010100,"Census Tract 101, Bergen County, New Jersey",5864,98987.0,364200.0,1832.0,3953.0,95.0,0.0,900.0,0.0,0.0,100.0,816.0
23,34003010200,"Census Tract 102, Bergen County, New Jersey",4275,75550.0,348600.0,1049.0,2514.0,146.0,26.0,716.0,0.0,0.0,85.0,805.0
24,34003010300,"Census Tract 103, Bergen County, New Jersey",7649,106750.0,356700.0,2508.0,4640.0,271.0,0.0,1152.0,0.0,0.0,64.0,1522.0
25,34003011100,"Census Tract 111, Bergen County, New Jersey",4293,68442.0,326100.0,836.0,1969.0,208.0,8.0,401.0,0.0,42.0,145.0,1528.0
26,34003011200,"Census Tract 112, Bergen County, New Jersey",5077,69310.0,353400.0,900.0,2303.0,471.0,0.0,418.0,0.0,33.0,127.0,1725.0
27,34003011300,"Census Tract 113, Bergen County, New Jersey",4240,88045.0,343300.0,1041.0,2447.0,150.0,52.0,325.0,0.0,0.0,183.0,1083.0
28,34003011400,"Census Tract 114, Bergen County, New Jersey",6525,76709.0,375100.0,1490.0,4140.0,274.0,0.0,426.0,34.0,0.0,0.0,1651.0
29,34003012001,"Census Tract 120.01, Bergen County, New Jersey",5933,70769.0,410500.0,1978.0,2885.0,282.0,0.0,896.0,0.0,0.0,46.0,1824.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4670,36119014811,"Census Tract 148.11, Westchester County, New York",5773,134773.0,445700.0,1888.0,4553.0,206.0,0.0,201.0,0.0,41.0,36.0,736.0
4671,36119014901,"Census Tract 149.01, Westchester County, New York",6524,134797.0,638700.0,2367.0,5634.0,18.0,33.0,236.0,0.0,0.0,46.0,557.0
4672,36119014903,"Census Tract 149.03, Westchester County, New York",4526,87746.0,443400.0,2104.0,4265.0,17.0,35.0,3.0,0.0,0.0,0.0,206.0
4673,36119014907,"Census Tract 149.07, Westchester County, New York",4255,110610.0,395500.0,1241.0,3452.0,151.0,17.0,185.0,0.0,0.0,1.0,449.0
4674,36119014908,"Census Tract 149.08, Westchester County, New York",2918,138571.0,614400.0,1034.0,2572.0,2.0,0.0,148.0,0.0,0.0,30.0,166.0
4675,36119014909,"Census Tract 149.09, Westchester County, New York",2907,104286.0,432600.0,1528.0,2577.0,0.0,0.0,148.0,0.0,0.0,0.0,182.0
4676,36119015000,"Census Tract 150, Westchester County, New York",5178,126724.0,584300.0,2239.0,4366.0,103.0,28.0,82.0,0.0,27.0,201.0,377.0
4677,36119981000,"Census Tract 9810, Westchester County, New York",1921,57353.0,-666666666.0,381.0,676.0,549.0,0.0,353.0,0.0,9.0,4.0,330.0
4678,36119982000,"Census Tract 9820, Westchester County, New York",1562,-666666666.0,-666666666.0,46.0,175.0,809.0,0.0,68.0,0.0,0.0,14.0,496.0
4679,36119983000,"Census Tract 9830, Westchester County, New York",1331,-666666666.0,-666666666.0,112.0,554.0,465.0,46.0,6.0,0.0,0.0,84.0,176.0
4680,36119984000,"Census Tract 9840, Westchester County, New York",288,38929.0,-666666666.0,52.0,149.0,97.0,0.0,0.0,0.0,0.0,4.0,38.0
4681,36119985000,"Census Tract 9850, Westchester County, New York",2485,-666666666.0,-666666666.0,15.0,1567.0,324.0,13.0,104.0,10.0,0.0,59.0,417.0
4682,42103950102,"Census Tract 9501.02, Pike County, Pennsylvania",2383,57292.0,188200.0,467.0,2077.0,7.0,0.0,24.0,0.0,15.0,6.0,254.0
4683,42103950103,"Census Tract 9501.03, Pike County, Pennsylvania",2336,55833.0,174600.0,450.0,2013.0,10.0,15.0,19.0,6.0,22.0,122.0,129.0
4684,42103950104,"Census Tract 9501.04, Pike County, Pennsylvania",2311,53789.0,215500.0,407.0,2128.0,14.0,9.0,27.0,0.0,0.0,15.0,127.0
4685,42103950201,"Census Tract 9502.01, Pike County, Pennsylvania",3470,69554.0,225200.0,722.0,2665.0,362.0,0.0,0.0,0.0,34.0,56.0,353.0
4686,42103950202,"Census Tract 9502.02, Pike County, Pennsylvania",1562,51016.0,180700.0,223.0,1330.0,107.0,0.0,0.0,0.0,0.0,69.0,56.0
4687,42103950301,"Census Tract 9503.01, Pike County, Pennsylvania",2494,50129.0,182400.0,640.0,2381.0,28.0,0.0,0.0,0.0,0.0,58.0,27.0
4688,42103950302,"Census Tract 9503.02, Pike County, Pennsylvania",771,61875.0,336500.0,265.0,745.0,0.0,8.0,18.0,0.0,0.0,0.0,0.0
4689,42103950501,"Census Tract 9505.01, Pike County, Pennsylvania",1578,52470.0,197400.0,171.0,1197.0,81.0,0.0,6.0,0.0,12.0,61.0,221.0
4690,42103950502,"Census Tract 9505.02, Pike County, Pennsylvania",3132,57875.0,205300.0,728.0,2186.0,237.0,0.0,120.0,0.0,31.0,75.0,483.0
4691,42103950601,"Census Tract 9506.01, Pike County, Pennsylvania",1560,68319.0,269200.0,354.0,1404.0,33.0,0.0,11.0,0.0,0.0,53.0,59.0
4692,42103950603,"Census Tract 9506.03, Pike County, Pennsylvania",1093,56250.0,281400.0,255.0,1009.0,16.0,0.0,0.0,0.0,0.0,16.0,52.0
4693,42103950605,"Census Tract 9506.05, Pike County, Pennsylvania",6056,83220.0,207100.0,1048.0,5487.0,333.0,21.0,0.0,9.0,11.0,0.0,195.0
4694,42103950606,"Census Tract 9506.06, Pike County, Pennsylvania",5647,86250.0,237300.0,1369.0,4951.0,71.0,0.0,156.0,0.0,12.0,20.0,437.0
4695,42103950701,"Census Tract 9507.01, Pike County, Pennsylvania",4107,61726.0,155800.0,537.0,3665.0,12.0,0.0,67.0,0.0,0.0,26.0,337.0
4696,42103950702,"Census Tract 9507.02, Pike County, Pennsylvania",3119,59239.0,151100.0,405.0,2908.0,44.0,0.0,60.0,0.0,0.0,19.0,88.0
4697,42103950801,"Census Tract 9508.01, Pike County, Pennsylvania",4403,55530.0,120000.0,718.0,2777.0,705.0,0.0,53.0,0.0,0.0,97.0,771.0
4698,42103950802,"Census Tract 9508.02, Pike County, Pennsylvania",6004,50724.0,146700.0,795.0,3072.0,970.0,20.0,44.0,0.0,0.0,11.0,1887.0
4699,42103950900,"Census Tract 9509, Pike County, Pennsylvania",4184,49453.0,146100.0,721.0,3888.0,55.0,29.0,22.0,0.0,0.0,9.0,181.0

Oops, that's a little long. Maybe we just want to see the first 10 rows:

In [4]:
census_data.head(10)

,geoid,name,total_population,median_income,median_home_value,educational_attainment,white_alone,black_alone,native,asian,native_hawaiian_pacific_islander,some_other_race_alone,two_or_more,hispanic_or_latino
0,34003001000,"Census Tract 10, Bergen County, New Jersey",6767,151641.0,680000.0,3045.0,5667.0,75.0,0.0,759.0,0.0,0.0,132.0,134.0
1,34003002100,"Census Tract 21, Bergen County, New Jersey",1522,114545.0,2000001.0,836.0,788.0,141.0,0.0,444.0,0.0,0.0,27.0,122.0
2,34003002200,"Census Tract 22, Bergen County, New Jersey",5389,90647.0,453800.0,1791.0,3481.0,99.0,9.0,1247.0,0.0,36.0,19.0,504.0
3,34003002300,"Census Tract 23, Bergen County, New Jersey",5828,112031.0,610000.0,2363.0,3595.0,89.0,37.0,1627.0,0.0,0.0,32.0,448.0
4,34003003100,"Census Tract 31, Bergen County, New Jersey",4946,76906.0,301900.0,1588.0,1803.0,306.0,0.0,1435.0,0.0,13.0,24.0,1365.0
5,34003003200,"Census Tract 32, Bergen County, New Jersey",5044,69531.0,322400.0,1417.0,1342.0,186.0,19.0,1882.0,0.0,6.0,64.0,1564.0
6,34003003300,"Census Tract 33, Bergen County, New Jersey",6638,97957.0,328100.0,1737.0,2437.0,400.0,0.0,2131.0,0.0,0.0,148.0,1522.0
7,34003003401,"Census Tract 34.01, Bergen County, New Jersey",2958,122650.0,385200.0,941.0,1704.0,109.0,0.0,520.0,0.0,0.0,36.0,589.0
8,34003003402,"Census Tract 34.02, Bergen County, New Jersey",3827,105776.0,356100.0,1237.0,1937.0,260.0,0.0,733.0,0.0,4.0,122.0,771.0
9,34003003500,"Census Tract 35, Bergen County, New Jersey",4100,52382.0,340200.0,891.0,886.0,502.0,16.0,1160.0,0.0,0.0,59.0,1493.0

Or the last four:

In [5]:
census_data.tail(4)

,geoid,name,total_population,median_income,median_home_value,educational_attainment,white_alone,black_alone,native,asian,native_hawaiian_pacific_islander,some_other_race_alone,two_or_more,hispanic_or_latino
4696,42103950702,"Census Tract 9507.02, Pike County, Pennsylvania",3119,59239.0,151100.0,405.0,2908.0,44.0,0.0,60.0,0.0,0.0,19.0,88.0
4697,42103950801,"Census Tract 9508.01, Pike County, Pennsylvania",4403,55530.0,120000.0,718.0,2777.0,705.0,0.0,53.0,0.0,0.0,97.0,771.0
4698,42103950802,"Census Tract 9508.02, Pike County, Pennsylvania",6004,50724.0,146700.0,795.0,3072.0,970.0,20.0,44.0,0.0,0.0,11.0,1887.0
4699,42103950900,"Census Tract 9509, Pike County, Pennsylvania",4184,49453.0,146100.0,721.0,3888.0,55.0,29.0,22.0,0.0,0.0,9.0,181.0

or we want to know the length of the entire set:

In [6]:
len(census_data)

4700

In [7]:
census_data.T

,0,1,2,3,4,5,6,7,8,9,...,4690,4691,4692,4693,4694,4695,4696,4697,4698,4699
geoid,34003001000,34003002100,34003002200,34003002300,34003003100,34003003200,34003003300,34003003401,34003003402,34003003500,...,42103950502,42103950601,42103950603,42103950605,42103950606,42103950701,42103950702,42103950801,42103950802,42103950900
name,"Census Tract 10, Bergen County, New Jersey","Census Tract 21, Bergen County, New Jersey","Census Tract 22, Bergen County, New Jersey","Census Tract 23, Bergen County, New Jersey","Census Tract 31, Bergen County, New Jersey","Census Tract 32, Bergen County, New Jersey","Census Tract 33, Bergen County, New Jersey","Census Tract 34.01, Bergen County, New Jersey","Census Tract 34.02, Bergen County, New Jersey","Census Tract 35, Bergen County, New Jersey",...,"Census Tract 9505.02, Pike County, Pennsylvania","Census Tract 9506.01, Pike County, Pennsylvania","Census Tract 9506.03, Pike County, Pennsylvania","Census Tract 9506.05, Pike County, Pennsylvania","Census Tract 9506.06, Pike County, Pennsylvania","Census Tract 9507.01, Pike County, Pennsylvania","Census Tract 9507.02, Pike County, Pennsylvania","Census Tract 9508.01, Pike County, Pennsylvania","Census Tract 9508.02, Pike County, Pennsylvania","Census Tract 9509, Pike County, Pennsylvania"
total_population,6767,1522,5389,5828,4946,5044,6638,2958,3827,4100,...,3132,1560,1093,6056,5647,4107,3119,4403,6004,4184
median_income,151641,114545,90647,112031,76906,69531,97957,122650,105776,52382,...,57875,68319,56250,83220,86250,61726,59239,55530,50724,49453
median_home_value,680000,2e+06,453800,610000,301900,322400,328100,385200,356100,340200,...,205300,269200,281400,207100,237300,155800,151100,120000,146700,146100
educational_attainment,3045,836,1791,2363,1588,1417,1737,941,1237,891,...,728,354,255,1048,1369,537,405,718,795,721
white_alone,5667,788,3481,3595,1803,1342,2437,1704,1937,886,...,2186,1404,1009,5487,4951,3665,2908,2777,3072,3888
black_alone,75,141,99,89,306,186,400,109,260,502,...,237,33,16,333,71,12,44,705,970,55
native,0,0,9,37,0,19,0,0,0,16,...,0,0,0,21,0,0,0,0,20,29
asian,759,444,1247,1627,1435,1882,2131,520,733,1160,...,120,11,0,0,156,67,60,53,44,22
native_hawaiian_pacific_islander,0,0,0,0,0,0,0,0,0,0,...,0,0,0,9,0,0,0,0,0,0
some_other_race_alone,0,0,36,0,13,6,0,0,4,0,...,31,0,0,11,12,0,0,0,0,0
two_or_more,132,27,19,32,24,64,148,36,122,59,...,75,53,16,0,20,26,19,97,11,9
hispanic_or_latino,134,122,504,448,1365,1564,1522,589,771,1493,...,483,59,52,195,437,337,88,771,1887,181

### Playing with columns

How about selecting columns? This is how you can do that:

In [8]:
census_data['black_alone']

0        75.0
1       141.0
2        99.0
3        89.0
4       306.0
5       186.0
6       400.0
7       109.0
8       260.0
9       502.0
10      145.0
11      462.0
12        0.0
13      124.0
14       68.0
15      145.0
16      297.0
17       28.0
18       86.0
19       64.0
20       11.0
21       36.0
22       95.0
23      146.0
24      271.0
25      208.0
26      471.0
27      150.0
28      274.0
29      282.0
        ...
4670    206.0
4671     18.0
4672     17.0
4673    151.0
4674      2.0
4675      0.0
4676    103.0
4677    549.0
4678    809.0
4679    465.0
4680     97.0
4681    324.0
4682      7.0
4683     10.0
4684     14.0
4685    362.0
4686    107.0
4687     28.0
4688      0.0
4689     81.0
4690    237.0
4691     33.0
4692     16.0
4693    333.0
4694     71.0
4695     12.0
4696     44.0
4697    705.0
4698    970.0
4699     55.0
Name: black_alone, Length: 4700, dtype: float64

You can also select multiple columns:

In [9]:
column_names  = ['black_alone', 'native']
census_data[column_names]

      black_alone  native
0            75.0     0.0
1           141.0     0.0
2            99.0     9.0
3            89.0    37.0
4           306.0     0.0
5           186.0    19.0
6           400.0     0.0
7           109.0     0.0
8           260.0     0.0
9           502.0    16.0
10          145.0     0.0
11          462.0     0.0
12            0.0     9.0
13          124.0     0.0
14           68.0     0.0
15          145.0     0.0
16          297.0     0.0
17           28.0     8.0
18           86.0     0.0
19           64.0    14.0
20           11.0     0.0
21           36.0     6.0
22           95.0     0.0
23          146.0    26.0
24          271.0     0.0
25          208.0     8.0
26          471.0     0.0
27          150.0    52.0
28          274.0     0.0
29          282.0     0.0
...           ...     ...
4670        206.0     0.0
4671         18.0    33.0
4672         17.0    35.0
4673        151.0    17.0
4674          2.0     0.0
4675          0.0     0.0
4676        103.0    28.0
4677        549.0     0.0
4678        809.0     0.0
4679        465.0    46.0
4680         97.0     0.0
4681        324.0    13.0
4682          7.0     0.0
4683         10.0    15.0
4684         14.0     9.0
4685        362.0     0.0
4686        107.0     0.0
4687         28.0     0.0
4688          0.0     8.0
4689         81.0     0.0
4690        237.0     0.0
4691         33.0     0.0
4692         16.0     0.0
4693        333.0    21.0
4694         71.0     0.0
4695         12.0     0.0
4696         44.0     0.0
4697        705.0     0.0
4698        970.0    20.0
4699         55.0    29.0

[4700 rows x 2 columns]

### Doing math with your data
There are a few nifty functions you can apply to your data columns.

In [10]:
census_data['black_alone'].sum()

3155672.0

In [11]:
census_data['black_alone'].median()

198.5

In [12]:
census_data['black_alone'].mean()

671.4195744680851

There is also this nifty function which gives you a quick overview of your data:

In [13]:
census_data['black_alone'].describe()

count     4700.000000
mean       671.419574
std       1041.216791
min          0.000000
25%         47.000000
50%        198.500000
75%        889.500000
max      17123.000000
Name: black_alone, dtype: float64

### Making new data columns
You can make a new column based on two columns like so:

In [14]:
census_data['black_alone_percentage'] = census_data['black_alone']/census_data['total_population']

In [15]:
census_data.head()

,geoid,name,total_population,median_income,median_home_value,educational_attainment,white_alone,black_alone,native,asian,native_hawaiian_pacific_islander,some_other_race_alone,two_or_more,hispanic_or_latino,black_alone_percentage
0,34003001000,"Census Tract 10, Bergen County, New Jersey",6767,151641.0,680000.0,3045.0,5667.0,75.0,0.0,759.0,0.0,0.0,132.0,134.0,0.011083
1,34003002100,"Census Tract 21, Bergen County, New Jersey",1522,114545.0,2000001.0,836.0,788.0,141.0,0.0,444.0,0.0,0.0,27.0,122.0,0.092641
2,34003002200,"Census Tract 22, Bergen County, New Jersey",5389,90647.0,453800.0,1791.0,3481.0,99.0,9.0,1247.0,0.0,36.0,19.0,504.0,0.018371
3,34003002300,"Census Tract 23, Bergen County, New Jersey",5828,112031.0,610000.0,2363.0,3595.0,89.0,37.0,1627.0,0.0,0.0,32.0,448.0,0.015271
4,34003003100,"Census Tract 31, Bergen County, New Jersey",4946,76906.0,301900.0,1588.0,1803.0,306.0,0.0,1435.0,0.0,13.0,24.0,1365.0,0.061868

To overwrite your previous data you can just re-assign the column new values, the way you do with any variable:

In [16]:
census_data['black_alone_percentage'] = (census_data['black_alone']/census_data['total_population'])*100

In [17]:
census_data.head()

,geoid,name,total_population,median_income,median_home_value,educational_attainment,white_alone,black_alone,native,asian,native_hawaiian_pacific_islander,some_other_race_alone,two_or_more,hispanic_or_latino,black_alone_percentage
0,34003001000,"Census Tract 10, Bergen County, New Jersey",6767,151641.0,680000.0,3045.0,5667.0,75.0,0.0,759.0,0.0,0.0,132.0,134.0,1.108320
1,34003002100,"Census Tract 21, Bergen County, New Jersey",1522,114545.0,2000001.0,836.0,788.0,141.0,0.0,444.0,0.0,0.0,27.0,122.0,9.264126
2,34003002200,"Census Tract 22, Bergen County, New Jersey",5389,90647.0,453800.0,1791.0,3481.0,99.0,9.0,1247.0,0.0,36.0,19.0,504.0,1.837076
3,34003002300,"Census Tract 23, Bergen County, New Jersey",5828,112031.0,610000.0,2363.0,3595.0,89.0,37.0,1627.0,0.0,0.0,32.0,448.0,1.527111
4,34003003100,"Census Tract 31, Bergen County, New Jersey",4946,76906.0,301900.0,1588.0,1803.0,306.0,0.0,1435.0,0.0,13.0,24.0,1365.0,6.186818

A quick sorting function can now help you find the spots with the highest or lowest black populations (we can go over this again next week):

In [18]:
census_data.sort_values(by='median_income', ascending = True)

,geoid,name,total_population,median_income,median_home_value,educational_attainment,white_alone,black_alone,native,asian,native_hawaiian_pacific_islander,some_other_race_alone,two_or_more,hispanic_or_latino,black_alone_percentage
3712,36081062400,"Census Tract 624, Queens County, New York",0,-666666666.0,-666666666.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
3952,36081156700,"Census Tract 1567, Queens County, New York",1382,-666666666.0,663500.0,218.0,324.0,255.0,0.0,500.0,0.0,0.0,10.0,293.0,18.451520
1546,36005017100,"Census Tract 171, Bronx County, New York",0,-666666666.0,-666666666.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
2533,36047096000,"Census Tract 960, Kings County, New York",0,-666666666.0,-666666666.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
3928,36081138502,"Census Tract 1385.02, Queens County, New York",37,-666666666.0,-666666666.0,17.0,16.0,4.0,0.0,0.0,0.0,0.0,0.0,17.0,10.810811
1540,36005016300,"Census Tract 163, Bronx County, New York",0,-666666666.0,-666666666.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
2601,36047118000,"Census Tract 1180, Kings County, New York",0,-666666666.0,-666666666.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
3905,36081121100,"Census Tract 1211, Queens County, New York",0,-666666666.0,-666666666.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
3513,36081029900,"Census Tract 299, Queens County, New York",0,-666666666.0,-666666666.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
1506,36005011000,"Census Tract 110, Bronx County, New York",151,-666666666.0,-666666666.0,37.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,151.0,0.000000
801,34025804700,"Census Tract 8047, Monmouth County, New Jersey",7,-666666666.0,-666666666.0,1.0,5.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.000000
2621,36047990100,"Census Tract 9901, Kings County, New York",0,-666666666.0,-666666666.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
3326,36081005000,"Census Tract 50, Queens County, New York",62,-666666666.0,-666666666.0,22.0,18.0,0.0,4.0,0.0,0.0,0.0,0.0,44.0,0.000000
3316,36081003700,"Census Tract 37, Queens County, New York",0,-666666666.0,-666666666.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
3960,36081990100,"Census Tract 9901, Queens County, New York",0,-666666666.0,-666666666.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
4542,36119005600,"Census Tract 56, Westchester County, New York",0,-666666666.0,-666666666.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
3190,36061031100,"Census Tract 311, New York County, New York",0,-666666666.0,-666666666.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
3185,36061029700,"Census Tract 297, New York County, New York",18,-666666666.0,-666666666.0,0.0,0.0,18.0,0.0,0.0,0.0,0.0,0.0,0.0,100.000000
3872,36081107202,"Census Tract 1072.02, Queens County, New York",0,-666666666.0,-666666666.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
1458,36005003700,"Census Tract 37, Bronx County, New York",279,-666666666.0,-666666666.0,12.0,56.0,60.0,0.0,0.0,0.0,0.0,0.0,163.0,21.505376
1450,36005002400,"Census Tract 24, Bronx County, New York",123,-666666666.0,-666666666.0,65.0,58.0,65.0,0.0,0.0,0.0,0.0,0.0,0.0,52.845528
3155,36061024000,"Census Tract 240, New York County, New York",1742,-666666666.0,-666666666.0,103.0,386.0,883.0,14.0,51.0,31.0,10.0,11.0,356.0,50.688863
3858,36081099900,"Census Tract 999, Queens County, New York",0,-666666666.0,-666666666.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
1443,36005000100,"Census Tract 1, Bronx County, New York",7503,-666666666.0,-666666666.0,76.0,510.0,4496.0,14.0,135.0,0.0,34.0,74.0,2240.0,59.922698
3524,36081033100,"Census Tract 331, Queens County, New York",0,-666666666.0,-666666666.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
3548,36081038301,"Census Tract 383.01, Queens County, New York",0,-666666666.0,-666666666.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
3549,36081038302,"Census Tract 383.02, Queens County, New York",0,-666666666.0,-666666666.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
3827,36081091800,"Census Tract 918, Queens County, New York",7,-666666666.0,-666666666.0,7.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
3826,36081091602,"Census Tract 916.02, Queens County, New York",0,-666666666.0,-666666666.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
3193,36061031900,"Census Tract 319, New York County, New York",0,-666666666.0,-666666666.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2845,36059518201,"Census Tract 5182.01, Nassau County, New York",4319,207250.0,1518100.0,2142.0,3677.0,64.0,0.0,337.0,0.0,10.0,20.0,211.0,1.481824
2939,36061003300,"Census Tract 33, New York County, New York",5030,207460.0,2000001.0,3196.0,3716.0,144.0,0.0,521.0,0.0,0.0,275.0,374.0,2.862823
4627,36119012303,"Census Tract 123.03, Westchester County, New York",4815,207656.0,928600.0,2415.0,4136.0,35.0,0.0,258.0,0.0,0.0,28.0,358.0,0.726895
2973,36061006900,"Census Tract 69, New York County, New York",2442,209167.0,1168600.0,1631.0,1900.0,49.0,0.0,237.0,0.0,20.0,74.0,162.0,2.006552
1873,36047002100,"Census Tract 21, Kings County, New York",4628,211071.0,1368600.0,2918.0,3410.0,151.0,0.0,389.0,0.0,0.0,357.0,321.0,3.262748
2771,36059412600,"Census Tract 4126, Nassau County, New York",3807,215313.0,891000.0,1823.0,3488.0,1.0,0.0,102.0,0.0,43.0,0.0,173.0,0.026267
536,34017018302,"Census Tract 183.02, Hudson County, New Jersey",3726,216300.0,836800.0,2835.0,2737.0,41.0,0.0,554.0,0.0,0.0,103.0,291.0,1.100376
4597,36119010100,"Census Tract 101, Westchester County, New York",4754,217273.0,903800.0,2619.0,3651.0,81.0,0.0,731.0,0.0,0.0,171.0,120.0,1.703828
2837,36059517701,"Census Tract 5177.01, Nassau County, New York",8099,218125.0,1590400.0,3937.0,5840.0,163.0,0.0,1678.0,0.0,12.0,119.0,287.0,2.012594
535,34017018301,"Census Tract 183.01, Hudson County, New Jersey",2375,218173.0,1078700.0,1720.0,1816.0,0.0,0.0,330.0,0.0,0.0,54.0,175.0,0.000000
4641,36119013201,"Census Tract 132.01, Westchester County, New York",4316,220855.0,810800.0,2126.0,3331.0,127.0,0.0,374.0,8.0,18.0,79.0,379.0,2.942539
2638,36059301700,"Census Tract 3017, Nassau County, New York",2719,222083.0,1420000.0,1424.0,2414.0,0.0,0.0,190.0,0.0,0.0,47.0,68.0,0.000000
4136,36103110101,"Census Tract 1101.01, Suffolk County, New York",3696,223036.0,1373400.0,1783.0,3332.0,10.0,0.0,165.0,0.0,0.0,49.0,140.0,0.270563
1404,34039036500,"Census Tract 365, Union County, New Jersey",5417,225074.0,877700.0,2819.0,4542.0,44.0,0.0,351.0,0.0,55.0,94.0,331.0,0.812258
2838,36059517705,"Census Tract 5177.05, Nassau County, New York",2793,229318.0,1918600.0,1382.0,2185.0,50.0,0.0,429.0,0.0,0.0,9.0,120.0,1.790190
4628,36119012304,"Census Tract 123.04, Westchester County, New York",4813,230357.0,1121500.0,2564.0,4330.0,45.0,0.0,185.0,0.0,8.0,96.0,149.0,0.934968
3071,36061016001,"Census Tract 160.01, New York County, New York",3918,233529.0,2000001.0,2662.0,3215.0,12.0,0.0,307.0,0.0,0.0,115.0,269.0,0.306279
3047,36061014200,"Census Tract 142, New York County, New York",4186,235083.0,2000001.0,2762.0,3877.0,11.0,0.0,130.0,0.0,32.0,68.0,68.0,0.262781
4640,36119013104,"Census Tract 131.04, Westchester County, New York",6066,237500.0,947400.0,3170.0,5214.0,98.0,47.0,439.0,0.0,0.0,34.0,234.0,1.615562
4578,36119008500,"Census Tract 85, Westchester County, New York",3258,241250.0,2000001.0,1715.0,2868.0,5.0,0.0,191.0,0.0,0.0,0.0,194.0,0.153468
320,34013016200,"Census Tract 162, Essex County, New Jersey",3387,244375.0,707100.0,2029.0,2867.0,150.0,0.0,114.0,0.0,14.0,79.0,163.0,4.428698
4596,36119010000,"Census Tract 100, Westchester County, New York",5387,250001.0,1438000.0,2956.0,4216.0,44.0,0.0,864.0,0.0,12.0,157.0,94.0,0.816781
4540,36119005400,"Census Tract 54, Westchester County, New York",1593,250001.0,988300.0,839.0,1256.0,35.0,0.0,36.0,0.0,0.0,78.0,188.0,2.197112
4595,36119009900,"Census Tract 99, Westchester County, New York",3008,250001.0,2000001.0,1629.0,2305.0,3.0,0.0,327.0,0.0,0.0,67.0,306.0,0.099734
358,34013020000,"Census Tract 200, Essex County, New Jersey",5826,250001.0,1534600.0,3182.0,4334.0,28.0,0.0,1099.0,0.0,9.0,128.0,228.0,0.480604
4532,36119004700,"Census Tract 47, Westchester County, New York",3596,250001.0,2000001.0,1649.0,3234.0,51.0,0.0,132.0,0.0,0.0,52.0,127.0,1.418242
141,34003047300,"Census Tract 473, Bergen County, New Jersey",3138,250001.0,1033800.0,1472.0,2603.0,41.0,0.0,324.0,0.0,0.0,79.0,91.0,1.306565
2925,36061002100,"Census Tract 21, New York County, New York",6488,250001.0,2000001.0,4168.0,4811.0,96.0,0.0,998.0,0.0,0.0,281.0,302.0,1.479655
359,34013020100,"Census Tract 201, Essex County, New Jersey",4593,250001.0,1418300.0,2713.0,3653.0,16.0,0.0,721.0,0.0,0.0,100.0,103.0,0.348356
4594,36119009800,"Census Tract 98, Westchester County, New York",4535,250001.0,1309100.0,2558.0,3514.0,29.0,0.0,593.0,8.0,0.0,124.0,267.0,0.639471